[package]
name = "qtun"
version = "0.2.0"
authors = ["Max Lv <max.c.lv@gmail.com>"]
repository = "https://github.com/madeye/qtun"
license = "MIT"
edition = "2018"

[[bin]]
name = "qtun-client"
path = "src/client.rs"

[[bin]]
name = "qtun-server"
path = "src/server.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "0.5"
futures = "0.3"
rustls = "0.20"
rustls-pemfile  = "0.2.1"
rustls-native-certs = "0.6.1"
quinn = "0.8"
structopt = "0.3"
anyhow = "1.0"
tracing = "0.1"
log = "0.4"
env_logger = "0.7"
dirs = "2.0"
